language: php

matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
  fast_finish: true

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache
env:
  global:
    TEST_CONFIG="phpunit.xml.dist"

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

script:
  - vendor/bin/phpunit --configuration $TEST_CONFIG
  - git log $(git describe --abbrev=0 --tags)...HEAD --no-merges --pretty=format:"* [%h](http://github.com/${TRAVIS_REPO_SLUG}/commit/%H) %s (%cN)"

after_success:
  - travis_retry php ./vendor/bin/php-coveralls -v --config .coveralls.yml -v;
